server:
  port: 8080

spring:
  application:
    name: application
#  datasource:
#    dynamic:
#      primary: master
#      strict: false
#      datasource:
#        master:
#          url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
#          username: postgres
#          password: postgres
#          driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  level:
    com.application.*: debug
